kind: Deployment
apiVersion: apps/v1
metadata:
  name: contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-nodejs-app
  template:
    metadata:
      labels:
        app: contacts-nodejs-app
    spec:
      containers:
        - name: contacts
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: contacts-nodejs-app-svc
spec:
ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
selector:
  app: contacts-nodejs-app
